"""MCP tools for the Module 8 and Module 9 integrations."""

import logging
import re
from collections.abc import Awaitable, Callable
from typing import Any

from mcp.server.mcpserver import MCPServer
from mcp.server.mcpserver.context import Context

from internal_tools_mcp.rag_service.rag_service import ask_question
from internal_tools_mcp.retrive_service.retrive_service import retrieve_documents


LOGGER = logging.getLogger("internal_tools_mcp.audit")
UUID_PATTERN = re.compile(
    r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
)


def _text(value: str, name: str, maximum: int) -> str:
    value = value.strip()
    if not value or len(value) > maximum:
        raise ValueError(f"{name} must contain 1 to {maximum} characters")
    return value


def _tenant_uuid(value: str) -> str:
    value = _text(value, "tenant_id", 36)
    if not UUID_PATTERN.fullmatch(value):
        raise ValueError("tenant_id must be a valid UUID")
    return value


def _caller(ctx: Context | None) -> str:
    if ctx is None:
        return "direct-call"
    try:
        return (ctx.request_context.request.headers or {}).get(
            "x-caller-id", "anonymous"
        )
    except (AttributeError, ValueError):
        return "stdio"


def _audit(name: str, arguments: dict[str, Any], ctx: Context | None) -> None:
    LOGGER.info(
        "tool_invocation tool=%s arguments=%s caller=%s", name, arguments, _caller(ctx)
    )


async def _default_answer(query: str, tenant_id: str) -> dict[str, object]:
    return await ask_question(query=query, tenant_id=tenant_id)


async def _default_retrieval(
    tenant_id: str,
    query: str,
    document_type: str | None,
    top_k: int,
) -> dict[str, object]:
    return await retrieve_documents(
        tenant_id=tenant_id,
        query=query,
        document_type=document_type,
        top_k=top_k,
    )


def register_tools(
    mcp: MCPServer,
    answer_service: Callable[[str, str], Awaitable[dict[str, object]]] | None = None,
    retrieval_service: Callable[
        [str, str, str | None, int], Awaitable[dict[str, object]]
    ]
    | None = None,
) -> None:
    """Register all application tools on the supplied MCP server."""

    answer = answer_service or _default_answer
    retrieval = retrieval_service or _default_retrieval

    @mcp.tool(description="Answer a question with Module 9's RAGChat service.")
    async def module9_chat_answer(
        query: str,
        tenant_id: str,
        ctx: Context | None = None,
    ) -> dict[str, object]:
        """Return an answer generated by the Module 9 RAG pipeline."""

        _audit("module9_chat_answer", {"query": query, "tenant_id": tenant_id}, ctx)
        query = _text(query, "query", 2000)
        tenant_id = _tenant_uuid(tenant_id)
        return await answer(query, tenant_id)

    @mcp.tool(
        description="Retrieve tenant-scoped documents with Module 8's vector search service."
    )
    async def module8_retrieve_documents(
        tenant_id: str,
        query: str,
        document_type: str | None = None,
        top_k: int = 5,
        ctx: Context | None = None,
    ) -> dict[str, object]:
        """Return documents from Module 8's read-only retrieval pipeline."""

        _audit(
            "module8_retrieve_documents",
            {
                "tenant_id": tenant_id,
                "query": query,
                "document_type": document_type,
                "top_k": top_k,
            },
            ctx,
        )
        tenant_id = _text(tenant_id, "tenant_id", 200)
        query = _text(query, "query", 2000)
        if document_type is not None:
            document_type = _text(document_type, "document_type", 100)
        if not 1 <= top_k <= 50:
            raise ValueError("top_k must be between 1 and 50")
        return await retrieval(tenant_id, query, document_type, top_k)
