[project]
name = "module-01-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.120.0",
    "anyio>=4.14.2",
    "dotenv>=0.9.9",
    "google-genai>=2.14.0",
    "httpx>=0.28.1",
    "openai>=2.47.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-tornasync>=0.6.0.post2",
    "pytest-trio>=0.8.0",
]
