services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector_db_framework
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_search
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
    postgres_data:
      external: true
      name: module-08-vectordb_postgres_data
